/**********************************************************************************************************************
 * \file Asclin0.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/

#include "Ifx_Types.h"
#include "IfxAsclin_Asc.h"
#include "IfxPort.h"
#include "Device_Driver/Asclin0.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define USB_UART_MAX_PRINT_SIZE (255)

#define ASC0_TX_BUFFER_SIZE          256                                     /* Define the TX buffer size in byte    */
#define ASC0_RX_BUFFER_SIZE          256                                     /* Define the RX buffer size in byte    */
#define ASC0_BAUDRATE                115200                                  /* Define the UART baud rate            */


/* RXB/P15.2, TX/P15.3 */
#define _M_USB_TX_OUT           IfxAsclin0_TX_P15_2_OUT
#define _M_USB_RX_IN            IfxAsclin0_RXB_P15_3_IN


/* USB - ASCLIN3 */
/* 함수들이랑 변수들 이름만 ASCLIN3이고 실제로는 ASCLIN0임 ㅋㅋ*/
#define ISR_PRIORITY_ASCLIN0_TX     0x33    /* Priority for interrupt ASCLIN3 Transmit  */
#define ISR_PRIORITY_ASCLIN0_RX     0x35    /* Priority for interrupt ASCLIN3 Receive   */
#define ISR_PRIORITY_ASCLIN0_ER     0x34    /* Priority for interrupt ASCLIN3 Errors    */
#define TC375_to_RPI_MAX_DATA_SIZE 4
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
static IfxAsclin_Asc s_asclin0;
static uint8 s_asclin0_tx_buf[ASC0_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 s_asclin0_rx_buf[ASC0_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 asclin0_rxflag = 0;
static uint8 rxdata[32];
static uint8 prev_data = 0;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/

IFX_INTERRUPT(asclin0_tx_ISR, 0, ISR_PRIORITY_ASCLIN0_TX);
void asclin0_tx_ISR (void)
{
    IfxAsclin_Asc_isrTransmit(&s_asclin0);
    // 이게 없으면 첫 문자만 보내지고 그 이후에는 전송이 안됨.
}

IFX_INTERRUPT(asclin0_rx_ISR, 0, ISR_PRIORITY_ASCLIN0_RX);
void asclin0_rx_ISR (void)
{
    IfxAsclin_Asc_isrReceive(&s_asclin0);
    asclin0_rxflag=1;
}

IFX_INTERRUPT(asclin0_err_ISR, 0, ISR_PRIORITY_ASCLIN0_ER);
void asclin0_err_ISR (void)
{
    ;
}

void Asclin0_Init(void)
{
    /* ======================= init_asclin3 ======================= */
       IfxAsclin_Asc_Config asc_conf;

       /* Set default configurations */
       IfxAsclin_Asc_initModuleConfig(&asc_conf, &MODULE_ASCLIN0); /* Initialize the structure with default values      */

       /* Set the desired baud rate */
       asc_conf.baudrate.baudrate = ASC0_BAUDRATE; /* Set the baud rate in bit/s       */
       asc_conf.baudrate.oversampling = IfxAsclin_OversamplingFactor_16; /* Set the oversampling factor      */

       /* Configure the sampling mode */
       asc_conf.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three; /* Set the number of samples per bit*/
       asc_conf.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8; /* Set the first sample position    */

       /* ISR priorities and interrupt target */
       asc_conf.interrupt.txPriority = ISR_PRIORITY_ASCLIN0_TX; /* Set the interrupt priority for TX events             */
       asc_conf.interrupt.rxPriority = ISR_PRIORITY_ASCLIN0_RX; /* Set the interrupt priority for RX events             */
       asc_conf.interrupt.erPriority = ISR_PRIORITY_ASCLIN0_ER; /* Set the interrupt priority for Error events          */
       asc_conf.interrupt.typeOfService = IfxSrc_Tos_cpu0;

       /* Pin configuration */
       const IfxAsclin_Asc_Pins pins = {.cts = NULL_PTR, /* CTS pin not used                                     */
       .ctsMode = IfxPort_InputMode_pullUp, .rx = &_M_USB_RX_IN, /* Select the pin for RX connected to the USB port      */
       .rxMode = IfxPort_InputMode_pullUp, /* RX pin                                               */
       .rts = NULL_PTR, /* RTS pin not used                                     */
       .rtsMode = IfxPort_OutputMode_pushPull, .tx = &_M_USB_TX_OUT, /* Select the pin for TX connected to the USB port      */
       .txMode = IfxPort_OutputMode_pushPull, /* TX pin                                               */
       .pinDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1};
       asc_conf.pins = &pins;

       /* FIFO buffers configuration */
       asc_conf.txBuffer = s_asclin0_tx_buf; /* Set the transmission buffer                          */
       asc_conf.txBufferSize = ASC0_TX_BUFFER_SIZE; /* Set the transmission buffer size                     */
       asc_conf.rxBuffer = s_asclin0_rx_buf; /* Set the receiving buffer                             */
       asc_conf.rxBufferSize = ASC0_RX_BUFFER_SIZE; /* Set the receiving buffer size                        */

       /* Init ASCLIN module */
       IfxAsclin_Asc_initModule(&s_asclin0, &asc_conf); /* Initialize the module with the given configuration   */
}
uint8* Asclin0_Receive(void)
{
    memset(rxdata, 0, sizeof(rxdata));
     if(asclin0_rxflag > 0)
     {
         int length = 0;
         uint8 data = IfxAsclin_Asc_blockingRead(&s_asclin0);
         while(1)
         {
            if(prev_data == 0xBE && data == 0xC1)
            {
                break;
            }
            rxdata[length++] = data;
            prev_data = data;
            data = IfxAsclin_Asc_blockingRead(&s_asclin0);
         }

         asclin0_rxflag = 0;
         return rxdata;
     }
     return NULL;
}

void Asclin0_Send(uint8 *data, uint16 length)
{
    for (uint16 i = 0; i < length; i++)
    {
        IfxAsclin_Asc_blockingWrite(&s_asclin0, data[i]);
        IfxAsclin_Asc_isrTransmit(&s_asclin0);
    }
    IfxAsclin_Asc_isrTransmit(&s_asclin0);
}
/*********************************************************************************************************************/
