/**********************************************************************************************************************
 * \file UartPacket.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef UARTPACKET_H_
#define UARTPACKET_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
//typedef struct
//{
//    uint8 door_request_from_app;
//    uint16 target_speed;
//    uint8 taxi_working;
//    uint8 operation;
//    uint8 is_Arrived;
//    uint16 yaw_rate;
//    uint8 yaw_rate_sign;
//    uint32 Stable_Flag;
//} RxPacket;
//
//typedef struct
//{
//    uint16 speed_fdb;
//    uint16 yaw_rate_fdb;
//    uint8 yaw_rate_sign_fdb;
//    uint8 door_status_for_rpi;
//    uint16 is_End;
//    uint8 obstacle_detected;
//    uint16 left_wheel_speed;
//    uint16 right_wheel_speed;
//} TxPacket;


typedef struct
{
    uint32 Stable_Flag;
    uint16 target_speed;
    uint16 yaw_rate;
    uint8 door_request_from_app;
    uint8 taxi_working;
    uint8 operation;
    uint8 is_Arrived;
    uint8 yaw_rate_sign;
} RxPacket;

typedef struct
{
    uint16 speed_fdb;
    uint16 yaw_rate_fdb;
    uint16 left_wheel_speed;
    uint16 right_wheel_speed;
    uint8 yaw_rate_sign_fdb;
    uint8 door_status_for_rpi;
    uint8 is_End;
    uint8 obstacle_detected;
} TxPacket;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void UartPacket_Init(void);
RxPacket UartPacket_from_Rpi(void);
void UartPacket_to_Rpi(TxPacket mytxdata);
#endif /* UARTPACKET_H_ */
