/**********************************************************************************************************************
 * \file UartPacket.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "UartPacket.h"
#include "Device_Driver/Asclin0.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define TC375_to_RPI_MAX_DATA_SIZE 5
#define RPI_to_TC375_MAX_DATA_SIZE 12
#define IDX_RX_TARGET_SPEED 0
#define IDX_RX_FLAG_VAL 2
#define IDX_RX_YAW_RATE 3
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
RxPacket _rxPacket;
uint8* getData;
uint8 txPacket[RPI_to_TC375_MAX_DATA_SIZE];

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void UartPacket_Init(void)
{
    Asclin0_Init();
}

RxPacket UartPacket_from_Rpi(void)
{
    _rxPacket.Stable_Flag = 0;
    getData = Asclin0_Receive();
    if (getData != NULL)
    {
        int idx = 0;
        while (idx < TC375_to_RPI_MAX_DATA_SIZE)
        {
            if (idx == IDX_RX_TARGET_SPEED)
            {
                _rxPacket.target_speed = ((uint16) getData[idx] | (((uint16) getData[idx + 1] & 0x0f) << 8)); // 목표 속도(m/s)
                idx+=2;
            }
            else if (idx == IDX_RX_FLAG_VAL)
            {
                _rxPacket.taxi_working = ((getData[idx] & 0x10) >> 4); // 택시 운행 정보 = (0:Default, 1:택시운행시작(isStart))
                _rxPacket.operation = ((getData[idx] & 0x0c) >> 2);    // 목표 방향 정보 = (0:STOP, 1:FORWARD, 2:BACKWARD)
                _rxPacket.is_Arrived = ((getData[idx] & 0x02) >> 1);   // 목적지 도착 여부 플래그 = (0:DEFAULT, 1:Destination Arrived)
                _rxPacket.door_request_from_app = (getData[idx] & 0x01); // 문 개폐 요청 = (0:Door_Close, 1:Door_Open)
                idx++;
            }
            else if (idx == IDX_RX_YAW_RATE)
            {
                _rxPacket.yaw_rate = ((uint16) getData[idx] | (((uint16) getData[idx + 2] & 0x3f) << 8)); // 목표 Yaw rate
                _rxPacket.yaw_rate_sign = (getData[idx + 1] & 0x08) >> 3; // Yaw Rate 값의 부호 플래그 (0:Plus, 1:Minus)
                idx += 3;
            }
            else
            {
                idx++;
            }
        }
        _rxPacket.Stable_Flag = 1;
        return _rxPacket;
    }

    //return NULL;
}
void UartPacket_to_Rpi(TxPacket mytxdata)
{

    txPacket[0] = (uint8)mytxdata.speed_fdb;
    txPacket[1] = ((mytxdata.speed_fdb >> 8) & 0x0f);
    txPacket[2] = (uint8)mytxdata.yaw_rate_fdb;
    txPacket[3] |= ((mytxdata.yaw_rate_sign_fdb << 3));
    txPacket[4] |= mytxdata.door_status_for_rpi;
    txPacket[4] |= (mytxdata.is_End << 1);
    txPacket[4] |= (mytxdata.obstacle_detected << 2);
    txPacket[5] = (mytxdata.yaw_rate_fdb >> 8) & 0x3f;
    txPacket[6]= (uint8)(mytxdata.left_wheel_speed);
    txPacket[7]= ((mytxdata.left_wheel_speed >> 8) & 0x03);
    txPacket[8]= (uint8)(mytxdata.right_wheel_speed);
    txPacket[9]= ((mytxdata.right_wheel_speed >> 8) & 0x03);
    txPacket[10] = 0xBE;
    txPacket[11] = 0xC1;
    Asclin0_Send(txPacket,RPI_to_TC375_MAX_DATA_SIZE);
    memset(txPacket,0,sizeof(txPacket));
}
