/**********************************************************************************************************************
 * \file MCU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "stdbool.h"
#include "Application/MCU.h"
#include "Application/AppScheduler.h"
#include "Device_Driver/Motor.h"
#include "Device_Driver/Can.h"
#include "Device_Driver/Asclin3.h"
#include "math.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/

static Gear_State operation;
static uint8 brake_operation;
static float32 target_speed_m_s;
static boolean taxi_status;
static boolean sign_target_speed;
static uint8 sign_yaw_rate;
static float32 yaw_rate;
static uint16 FDB_left_motor_velocity_m_s,FDB_right_motor_velocity_m_s;
static uint16 FDB_yaw_rate;
static boolean FDB_sign_yaw_rate;
static boolean power_brake_flag,soft_brake_flag,back_spin_flag;
static uint16 tmp_yaw_rate;
static Gear_State operation_tmp=D;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static void Can_Handler(void);
static void Event_10ms(void);
static void Send_Motor_Info(void);
static void Event_100ms(void);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


void MCU_Init(void)
{
    Asclin3_Init();
    App_Init();
    Can_Init();
    Motor_Init();
}
void MCU_Main(void)
{
    while(1)
    {
        Can_Handler();

        if(App_Check_Flag(FLAG_10MS))
        {
            App_Clear_Flag(FLAG_10MS);
            Motor_Event_10MS();
            Event_10ms();


        }

        if(App_Check_Flag(FLAG_100MS))
        {
            App_Clear_Flag(FLAG_100MS);
            if(soft_brake_flag)
            {
                Event_100ms();

            }

        }

        if(App_Check_Flag(FLAG_50MS))
        {
            App_Clear_Flag(FLAG_50MS);
            if(back_spin_flag)
            {
                Motor_BackSpin(operation_tmp);
                Motor_PowerBrake();
                back_spin_flag=FALSE;
                operation_tmp=D;
            }

            if(power_brake_flag)
            {
                Motor_Set_Power_Brake_Flag(power_brake_flag);
                Motor_BackSpin(operation_tmp);
                back_spin_flag=TRUE;
                operation_tmp=R;
            }
        }

    }
}
static void Can_Handler(void)
{
    CanMessage txmsg;
    CanMessage msg;
    if(Can_TxQueue_Pop(ECU, &txmsg))
    {
        Can_Message_Send(ECU,&txmsg);
    }
    if(Can_RxQueue_Pop(ECU,&msg))
    {
        switch(msg.id)
        {
            case MOTOR_CONTROL :
            {
                tmp_yaw_rate = (uint16)Can_Message_Parse(msg.dataLow, msg.dataHigh, 0, 16);
                uint16 tmp_target_speed_m_s=(uint16)Can_Message_Parse(msg.dataLow, msg.dataHigh, 16, 16);
                operation = (Gear_State)Can_Message_Parse(msg.dataLow, msg.dataHigh, 32, 2);
                taxi_status = (uint8)Can_Message_Parse(msg.dataLow, msg.dataHigh, 34, 1);
                sign_yaw_rate=Can_Message_Parse(msg.dataLow, msg.dataHigh, 35, 1);

                target_speed_m_s = ((float32)tmp_target_speed_m_s) / 100.0f;
                yaw_rate = ((float32)tmp_yaw_rate) / 1000.0f;
                yaw_rate = (sign_yaw_rate)? yaw_rate*-1 : yaw_rate;

                if(operation==B)
                {
                    soft_brake_flag=TRUE;
                }
                else
                {
                    soft_brake_flag=FALSE;
                }
            }
            break;

            case POWER_BRAKE :
            {
                power_brake_flag =(boolean)Can_Message_Parse(msg.dataLow, msg.dataHigh, 0, 1);

                Motor_Set_Power_Brake_Flag(power_brake_flag);
            }
            break;
        }
    }
}
static void Send_Motor_Info(void)
{
    CanMessage txmsg;
    Can_Message_Init(&txmsg, MOTOR_INFO_SEND_TO_CCU, 0x002, 8); //LEFT TOF

    Can_Message_AddSignal(&txmsg, 0, 16, FDB_left_motor_velocity_m_s);
    Can_Message_AddSignal(&txmsg, 16, 16, FDB_right_motor_velocity_m_s);
    Can_Message_AddSignal(&txmsg, 32, 16, FDB_yaw_rate);
    Can_Message_AddSignal(&txmsg, 48, 1, FDB_sign_yaw_rate);
    Can_TxQueue_Push(ECU, &txmsg);
}

static void Event_10ms(void)
{
    Motor_Get_Veclocity(&FDB_left_motor_velocity_m_s,&FDB_right_motor_velocity_m_s,&FDB_yaw_rate,&FDB_sign_yaw_rate);

    if(operation==D||operation==R||operation==B)
    {
        if(!power_brake_flag)  Motor_Move(yaw_rate,target_speed_m_s,D,power_brake_flag);
    }

    Send_Motor_Info();
}

static void Event_100ms(void)
{
    Motor_SoftBrake();
}

