/**********************************************************************************************************************
 * \file SCU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Application/SCU.h"
#include "Application/AppScheduler.h"
#include "Device_Driver/Can.h"
#include "Device_Driver/Tof.h"
#include "Device_Driver/Door.h"
#include "Device_Driver/Asclin3.h"

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
static uint32 f_distance,r_distance;
static boolean door_flag;
static boolean door_open_completed_tx_flag;

static boolean open_complete,close_complete;
static uint16 close_timeout;
static boolean close_timer_flag;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static void Event_10ms(void);
static void Event_100ms(void);
static void Event_1000ms(void);
static void Can_Handler(void);
static void Send_Tof_Msg(void);
static void Send_Door_Complete_Msg(void);
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void SCU_Init(void)
{
    Can_Init();
    Tof_Init();
    Door_Init();
    Asclin3_Init();
}
void SCU_Main(void)
{
    while(1)
    {
        Can_Handler();

        if(App_Check_Flag(FLAG_10MS)){
            App_Clear_Flag(FLAG_10MS);
            Event_10ms();
        }
        if(App_Check_Flag(FLAG_100MS)){
            App_Clear_Flag(FLAG_100MS);
            Event_100ms();
        }
        open_complete=Door_Open_Completed();
        close_complete=Door_Close_Completed();

        if(open_complete)
        {
            close_timer_flag =TRUE;
        }

    }
}
void Event_10ms(void)
{
    Send_Door_Complete_Msg();

    Tof_Write_Dummy(FRONT_TOF);
    Tof_Write_Dummy(REAR_TOF);

    f_distance =Tof_Read(FRONT_TOF);
    r_distance =Tof_Read(REAR_TOF);

    Send_Tof_Msg();
}

static void Event_100ms(void)
{
    if(door_flag==OPEN)
    {
        Door_Open();
    }

    else if(door_flag==CLOSE)
    {
        Door_Close();
    }
}

static void Event_1000ms(void)
{
//    if(close_timer_flag)
//    {
//        close_timeout++;
//        if(close_timeout>=5)
//        {
//            Door_Close();
//        }
//        close_timer_flag=FALSE;
//        close_timeout =0;
//    }
}
static void Can_Handler(void)
{
    CanMessage txmsg;
    CanMessage txmsg_tof;
    CanMessage msg;
    if(Can_TxQueue_Pop(ECU,&txmsg))
    {
        Can_Message_Send(ECU,&txmsg);
    }

    if(Can_TxQueue_Pop(TOFSENSOR,&txmsg_tof))
    {
        Can_Message_Send(TOFSENSOR,&txmsg_tof);
    }

    if(Can_RxQueue_Pop(ECU,&msg))
    {
        switch(msg.id)
        {
            case DOOR_MESSAGE :
            {

                door_flag =(boolean)Can_Message_Parse(msg.dataLow, msg.dataHigh, 0, 1);
            }
            break;
        }
    }
}
static void Send_Tof_Msg(void)
{
    CanMessage txmsg;
    Can_Message_Init(&txmsg, TOF_MESSAGE, 0x100, 8); //LEFT TOF

    Can_Message_AddSignal(&txmsg, 0, 24,f_distance);    //0x202
    Can_Message_AddSignal(&txmsg, 32,24,r_distance);    //0x201
    Can_TxQueue_Push(ECU,&txmsg);
}
static void Send_Door_Complete_Msg(void)
{
    CanMessage txmsg;
    Can_Message_Init(&txmsg, DOOR_OPEN_COMPLETE, 0x301, 1); //LEFT TOF
    Can_Message_AddSignal(&txmsg, 0, 1, Door_Open_Completed());
    Can_TxQueue_Push(ECU,&txmsg);

    CanMessage txmsg2;
    Can_Message_Init(&txmsg2, DOOR_CLOSE_COMPLETE, 0x302, 1); //LEFT TOF
    Can_Message_AddSignal(&txmsg2, 0, 1, Door_Close_Completed());
    Can_TxQueue_Push(ECU,&txmsg2);
}
